apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nginx-app
  annotations:
    version: v1.0.0
    description: "Customized version of nginx"
spec:
  components:
    - name: nginx
      type: webservice
      properties:
        image: nginx:1.20.0
        cpu: "0.1" 
        memory: 128Mi
        ports:
        - port: 80
          expose: true
      traits:
      - type: napptive-ingress         
        properties:
          name: nginx
          port: 80
          path: /
