apiVersion: core.napptive.com/v1alpha1
kind: ApplicationMetadata
name: "Redis"
version: 7.0.11
description: Redis
keywords:
  - "redis"
  - "database"
  - "key-value"
  - "in-memory"
license: "BSD-3-Clause license"
url: "https://redis.io/"
doc: "https://redis.io/docs/"
logo:
  - src: "https://storage.googleapis.com/artifacts.playground.napptive.dev/logos/redis.png"
    type: "image/png"
    size: "700x700"
