apiVersion: core.oam.dev/v1beta1
kind: Application 
metadata:
  name: gocd-application
spec:
  components:

    - name: gocd-server
      type: webservice
      properties:
        image: gocd/gocd-server:v23.3.0
        ports:
          - port: 8153
            expose: true
        cmd: ["/bin/bash",  "-c", "ls /config/ && mkdir -p /godata/config && cp /config/cruise-config.xml /godata/config && cp /secrets/password.properties /godata/config && /docker-entrypoint.sh"]
     
      traits:
        - type: napptive-ingress
          properties:
            name: gocd
            port: 8153
            path: /
        - type: storage
          properties:
            configMap:
              - name: gocd-config
                mountPath: /config/
            secret:
              - name: gocd-secret
                mountPath: /secrets/
      
    - name: gocd-agent
      type: webservice
      properties:
        image: napptive/gocd-agent-ubuntu-pg:latest
     
        env:
          - name: GO_SERVER_URL
            value: "http://gocd-server:8153/go" # Assuming SERVICE_HOST is defined
          - name: AGENT_AUTO_REGISTER_KEY
            value: 0e318c71-1449-41da-a40d-ea45d785d6d9
      dependsOn:
        - gocd-server

    - name: gocd-application
      type: k8s-objects
      properties:
        objects:
          - apiVersion: v1
            kind: Secret
            metadata:
              name: gocd-secret
            type: Opaque
            data:
              password.properties: |
                YWRtaW46JDJ5JDA1JGFRbHBSc0tYLmI4N01UMnRDbWNiMGU0V3Z1ZkphRWJnMUM2aFJkWjA4dXZ1V1h0VEJNMUFh

          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: gocd-config
            data:
              cruise-config.xml: |
                <?xml version="1.0" encoding="utf-8"?>
                <cruise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cruise-config.xsd" schemaVersion="139">
                <server agentAutoRegisterKey="0e318c71-1449-41da-a40d-ea45d785d6d9" webhookSecret="a708b484-0e03-4988-a80f-ed8572071d42" serverId="258eb178-c2a1-400d-bcbc-51f19cbc4a8c" tokenGenerationKey="05b312f2-1d89-4d36-ad28-129100dc57e8">
                    <security>
                    <authConfigs>
                        <authConfig id="check-password" pluginId="cd.go.authentication.passwordfile">
                        <property>
                            <key>PasswordFilePath</key>
                            <value>/godata/config/password.properties</value>
                        </property>
                        </authConfig>
                    </authConfigs>
                    </security>
                    <artifacts>
                    <artifactsDir>artifacts</artifactsDir>
                    </artifacts>
                </server>
                </cruise>
